[package]
name = "tcp-socket"
version = "0.1.0"
authors = ["Nasato Goto <goto@mfeed.ad.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
